projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - app/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - app/graphql/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/graphql/API.ts
        docsFilePath: app/graphql
        region: ap-south-1
        apiId: kgiu455jyrhxljr3l7qf7ntkyi
        frontend: javascript
        framework: react
        maxDepth: 2
