projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-south-1
        apiId: 3qkvxca7wfdalhsit3ebjepktq
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
